#!/bin/sh
CLIARGS="$*"		# Grab any args passed to safe_callweaver
TTY=9			# TTY (if you want one) for CallWeaver to run on
CONSOLE=yes		# Whether or not you want a console
#NOTIFY=ben@alkaloid.net	# Who to notify about crashes
MACHINE=`hostname`      # To specify which machine has crashed when getting the mail
DUMPDROP=/tmp
OPBXSBINDIR=__CALLWEAVER_SBIN_DIR__

#
# Don't fork when running "safely"
#
OPBXARGS=""
if [ "$TTY" != "" ]; then
	if [ -c /dev/tty${TTY} ]; then
		TTY=tty${TTY}
	elif [ -c /dev/vc/${TTY} ]; then
		TTY=vc/${TTY}
	else
		echo "Cannot find your TTY (${TTY})" >&2
		exit 1
	fi
	OPBXARGS="${OPBXARGS} -vvvg"
	if [ "$CONSOLE" != "no" ]; then
		OPBXARGS="${OPBXARGS} -c"
	fi
fi
if [ ! -w ${DUMPDROP} ]; then	
	echo "Cannot write to ${DUMPDROP}" >&2
	exit 1
fi

#
# Let CallWeaver dump core
#
ulimit -c unlimited

#launch_callweaver()
#{
#}

run_callweaver()
{
	while :; do 

		if [ "$TTY" != "" ]; then
			cd /tmp
			stty sane < /dev/${TTY}
			${OPBXSBINDIR}/callweaver ${CLIARGS} ${OPBXARGS} >& /dev/${TTY} < /dev/${TTY}
		else
			cd /tmp
			${OPBXSBINDIR}/callweaver ${CLIARGS} ${OPBXARGS}
		fi
		EXITSTATUS=$?
		echo "CallWeaver ended with exit status $EXITSTATUS"
		if [ "$EXITSTATUS" = "0" ]; then
			# Properly shutdown....
			echo "CallWeaver shutdown normally."
			exit 0
		elif [ $EXITSTATUS -gt 128 ]; then
			let EXITSIGNAL=EXITSTATUS-128
			echo "CallWeaver exited on signal $EXITSIGNAL."
			if [ "$NOTIFY" != "" ]; then
				echo "CallWeaver on $MACHINE exited on signal $EXITSIGNAL.  Might want to take a peek." | \
				mail -s "CallWeaver Died" $NOTIFY
			fi
                        if [ -f /tmp/core ]; then
				mv /tmp/core ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
			fi
		else
			if [ "${EXITSTATUS}" = "0" ]; then
				echo "CallWeaver ended normally.  Aborting."
				exit 0
			else
				echo "CallWeaver died with code $EXITSTATUS."
	                        if [ -f /tmp/core ]; then
					mv /tmp/core ${DUMPDROP}/core.`hostname`-`date -Iseconds` &
				fi
			fi
		fi
		echo "Automatically restarting CallWeaver."
		sleep 4
	done
}

run_callweaver &
