#!/bin/bash
PPATH=$1
## Make sure we were called from Makefile

if [ "x$OPENPBXVERSIONNUM" = "x" ]; then
  echo " ** Do not call this script directly"
  exit
fi

## Create a pkgconfig spec file for 3rd party modules (pkg-config openpbx --cflags)

if [ ! -d $PPATH ]; then
  exit
fi

## Clean out CFLAGS for the spec file.

LOCAL_CFLAGS=`echo $CFLAGS | $(SED) -e 's/\s*-pipe\s*//g' | $(SED) -e 's/-[Wmp]\S*\s*//g' | \
  $(SED) -r -e 's/-I(include|\.\.\/include) //g' | \
  $(SED) -e 's/-DINSTALL_PREFIX=\S* //g' | \
  $(SED) -r -e 's/-DOPENPBX_VERSION=\S* //g' | \
  $(SED) -r -e 's/-DOPBXT(ETCDIR|LIBDIR|VARLIBDIR|VARRUNDIR|SPOOLDIR|LOGDIR|CONFPATH|MODDIR|AGIDIR)=\S* //g'`


cat <<EOF > $PPATH/openpbx.pc
install_prefix=$INSTALL_PREFIX
version_number=$OPENPBXVERSIONNUM
etcdir=$OPBXETCDIR
libdir=$OPBXLIBDIR
varlibdir=$OPBXVARLIBDIR
varrundir=$OPBXVARRUNDIR
spooldir=$OPBXSPOOLDIR
logdir=$OPBXLOGDIR
confpath=$OPBXCONFPATH
moddir=$MODULES_DIR
agidir=$AGI_DIR

Name: openpbx
Description: Open Source PBX and telephony toolkit
Version: $OPENPBXVERSION
Libs: $LIBS
Cflags: $LOCAL_CFLAGS
EOF
