#!/bin/bash
#
# chkconfig: - 99 15
# description: Open source PBX 
# processname: openpbx

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0

case "$1" in
  start)
	mkdir -p /dev/fax &>/dev/null && chown openpbx.openpbx /dev/fax
	echo -n $"Starting CallWeaver: "
	daemon /usr/sbin/openpbx
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/openpbx
	;;
  stop)
	echo -n $"Stopping CallWeaver: "
	killproc openpbx
	RETVAL=$?

	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/openpbx
	;;
  restart)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  reload)
	killproc openpbx -HUP
	status openpbx
	RETVAL=$?
	;;
  status)
	status openpbx
	RETVAL=$?
	;;
  *)
	echo "Usage: openpbx {start|stop|status|restart|reload}"
	exit 1
esac

exit $RETVAL

