Document: callweaver
Title: Debian callweaver Manual
Author: <insert document author here>
Abstract: This manual describes what callweaver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/callweaver/callweaver.sgml.gz

Format: postscript
Files: /usr/share/doc/callweaver/callweaver.ps.gz

Format: text
Files: /usr/share/doc/callweaver/callweaver.text.gz

Format: HTML
Index: /usr/share/doc/callweaver/html/index.html
Files: /usr/share/doc/callweaver/html/*.html

  
