Document: openpbx
Title: Debian openpbx Manual
Author: <insert document author here>
Abstract: This manual describes what openpbx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openpbx/openpbx.sgml.gz

Format: postscript
Files: /usr/share/doc/openpbx/openpbx.ps.gz

Format: text
Files: /usr/share/doc/openpbx/openpbx.text.gz

Format: HTML
Index: /usr/share/doc/openpbx/html/index.html
Files: /usr/share/doc/openpbx/html/*.html

  
