#!/bin/bash
#
# chkconfig: - 99 15
# description: Open source PBX 
# processname: openpbx

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0

case "$1" in
  start)
	echo -n "Starting OpenPBX: "
	daemon /opt/openpbx.org/sbin/openpbx
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/openpbx
	;;
  stop)
	echo -n "Shutting OpenPBX: "
	killproc openpbx
	RETVAL=$?

	echo
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/openpbx
	;;
  restart|reload)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  status)
	status openpbx
	RETVAL=$?
	;;
  *)
	echo "Usage: openpbx {start|stop|status|restart|reload}"
	exit 1
esac

exit $RETVAL

